# -*- coding: utf-8 -*-
"""tugas_7_progdas_magal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X0Tg2EKSlEcvlBsjV734dPNuzLc69QPE

###**1. Buatlah sebuah test file yang berisi satu paragraf dengan lebih dari 20 kalimat huruf kecil (lowercased sentences). Bacalah file tersebut, ubah huruf pertama dari setiap kalimat menjadi huruf kapital, dan tuliskan teks tersebut ke dalam file teks baru yang berisi satu kalimat pada setiap barisnya.**
"""

def kapitalisasi_kalimat(nama_file_masukan, nama_file_keluaran):
    # Baca isi file input
    with open(nama_file_masukan, 'r', encoding='utf-8') as file_masukan:
        teks = file_masukan.read().strip().lower()

    # Pisahkan teks menjadi kalimat-kalimat berdasarkan tanda titik
    kalimat_list = teks.split('.')

    # Siapkan list kosong untuk menampung kalimat hasil proses
    kalimat_dikapitalisasi = []

    # Looping tiap kalimat
    for kalimat in kalimat_list:
        kalimat = kalimat.strip()  # hapus spasi di awal dan akhir
        if kalimat != "":  # kalau kalimat tidak kosong
            kalimat_baru = kalimat.capitalize()  # ubah huruf pertama jadi kapital
            kalimat_dikapitalisasi.append(kalimat_baru)

    # Tulis hasil ke file baru, satu kalimat per baris
    with open(nama_file_keluaran, 'w', encoding='utf-8') as file_keluaran:
        for kalimat in kalimat_dikapitalisasi:
            file_keluaran.write(kalimat + '.\n')

    print(f"Teks hasil telah disimpan ke '{nama_file_keluaran}'")


# Jalankan fungsi
kapitalisasi_kalimat('teks_progdas_magal.txt', 'teks_kapital_perbaris.txt')

"""###**2. Temukan sebuah text file daring (online) yang berisi kamus Bahasa Inggris. Tulislah sebuah program yang menelusuri text file tersebut untuk menemukan compound words (kata majemuk). Program Anda harus menampilkan kata majemuk tersebut beserta dua kata penyusunnya. Sebagai contoh, kata “raincoat”adalah kata majemuk, sehingga program Anda harus menampilkan: raincoat = rain + coat.**"""

def cari_compound_word(nama_file):
    # Baca semua kata dari file dan simpan dalam list
    with open(nama_file, 'r', encoding='utf-8') as f:
        kamus = set(word.strip().lower() for word in f.readlines())

    # Minta input dari user
    kata = input("Masukkan kata majemuk (contoh: raincoat): ").lower()

    ditemukan = False  # Flag untuk tahu apakah kata majemuk ditemukan

    # Periksa semua kemungkinan pemisahan kata
    for i in range(1, len(kata)):
        kiri = kata[:i]
        kanan = kata[i:]
        if kiri in kamus and kanan in kamus:
            print(f"{kata} = {kiri} + {kanan}")
            ditemukan = True
            break

    if not ditemukan:
        print(f"Tidak ditemukan kombinasi kata pembentuk '{kata}' dalam kamus.")

# Jalankan fungsi
cari_compound_word('english_words.txt')

"""###**Modifikasi kode berikut sehingga:**
###**1. Apabila file tidak ditemukan maka eror akan ditangani lebih dulu dan user diminta memasukkan nama file kembali hingga betul, baru user diminta memasukkan angka baris yang diinginkan**
###**2. Apabila angka yang dimasukkan user tidak tersedia pada baris teks, maka minta user memasukkan terus angka baris yang diinginkan sampai betul**
"""

# Program untuk membaca baris tertentu dari file teks

while True:
    try:
        file_str = input("Masukkan nama file yang ingin dibuka: ")
        input_file = open(file_str, 'r', encoding='utf-8')
        break  # keluar dari loop kalau file berhasil dibuka
    except FileNotFoundError:
        print(f"File '{file_str}' tidak ditemukan. Coba lagi ya.\n")

# Baca semua baris dari file
lines = input_file.readlines()
total_baris = len(lines)

# Jika file kosong
if total_baris == 0:
    print("File kosong, tidak ada baris yang bisa dibaca.")
    input_file.close()
    exit()

# Minta nomor baris hingga valid
while True:
    try:
        find_line_str = input(f"Masukkan nomor baris (1 - {total_baris}): ")
        find_line_int = int(find_line_str)

        if 1 <= find_line_int <= total_baris:
            line_str = lines[find_line_int - 1].strip()  # ambil isi baris
            print(f"\n✅ Baris {find_line_int} dari file '{file_str}' adalah:\n{line_str}")
            break
        else:
            print(f"Baris {find_line_int} tidak ada. File hanya punya {total_baris} baris.\n")
    except ValueError:
        print("Masukkan hanya angka ya.\n")

# Tutup file
input_file.close()
print("\nSelesai. Program berakhir.")