# -*- coding: utf-8 -*-
"""tugas_progdas_9_minggu_10_magal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AD0nLVR0EstBi5ttdpM_P4K-AMzmrRdz
"""

from abc import ABC, abstractmethod

class Kendaraan():
  def __init__(self, nama_merek, tipe_kendaraan, mesin_kendaraan):
    self.nama_merek = nama_merek
    self.tipe_kendaraan = tipe_kendaraan
    self.mesin_kendaraan = mesin_kendaraan

  @abstractmethod
  def mulai_berjalan(self):
    pass

  def suara(self):
    pass

class Mobil(Kendaraan):
  def __init__(self, nama_merek, tipe_kendaraan, mesin_kendaraan, warna):
    super().__init__(nama_merek, tipe_kendaraan, mesin_kendaraan)
    self.warna = warna

  def warna_mobil(self):
    print(self.tipe_kendaraan, "warna", self.warna)

  def mulai_berjalan(self):
    print(self.tipe_kendaraan, "berjalan di atas aspal...")

  def suara(self):
    print("Vrooomm Vrooomm!")

class Pesawat(Kendaraan):
  def __init__(self, nama_merek, tipe_kendaraan, mesin_kendaraan):
    super().__init__(nama_merek, tipe_kendaraan, mesin_kendaraan)

  def mulai_berjalan(self):
    print(self.nama_merek, "mulai lepas landas...")

  def suara(self):
    print("Ngieng!!!")

class Kapal(Kendaraan):
  def __init__(self, nama_merek, tipe_kendaraan, mesin_kendaraan, ukuran):
    super().__init__(nama_merek, tipe_kendaraan, mesin_kendaraan)
    self.ukuran = ukuran

  def ukuran_kapal(self, ukuran):
    if int(ukuran) == 1:
      print(self.tipe_kendaraan, "berukuran kecil")
    elif ukuran == 2:
      print(self.tipe_kendaraan, "berukuran sedang")
    elif ukuran == 3:
      print(self.tipe_kendaraan, "berukuran besar")
    elif ukuran == 4:
      print(self.tipe_kendaraan, "Anda menyewa Kapal Pesiar?")
    else:
      print(self.tipe_kendaraan, "ukuran tidak diketahui")

  def mulai_berjalan(self):
    print(self.tipe_kendaraan, "berlayar di lautan...")

  def suara(self):
    print("Breeemm Breeemm!")

jet_boat = Kapal("Jet Boat", "Kendaraan Air", "Tenaga Jet", 1)
print(jet_boat.nama_merek)
print(jet_boat.tipe_kendaraan)
print(jet_boat.mesin_kendaraan)
jet_boat.ukuran_kapal(jet_boat.ukuran)
jet_boat.mulai_berjalan()
jet_boat.suara()